spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ChatRobot?useUnicode=true&characterEncoding=utf8&useSSL=false
server:
  port: 443
  ssl:
    key-store: classpath:XXXXXX.jks
    key-store-password: XXXXXX
    keyStoreType: JKS
    keyAlias: XXXXXX
